version: "2"
services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /blockPro-libp2p
    image: "stallingerl/libp2p-echo-example:0.0.6"
    hostname: peer1
    volumes:
      - .:/blockPro-libp2p
    #command: bash -c "npm run start1"
    container_name: peer1
    ports:
      - "8337:8337"
    stdin_open: true
    tty: true
    privileged: true
    networks:
      static:
        ipv4_address: 172.22.0.2
  peer2:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /blockPro-libp2p
    image: "stallingerl/libp2p-echo-example:0.0.6"
    hostname: peer2
    volumes:
      - .:/blockPro-libp2p
    #command: bash -c "npm run start2"
    container_name: peer2
    ports:
      - "8338:8338"
    stdin_open: true
    tty: true
    privileged: true
    networks:
      static:
        ipv4_address: 172.22.0.3

  peer3:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /blockPro-libp2p
    image: "stallingerl/libp2p-echo-example:0.0.6"
    hostname: peer3
    volumes:
      - .:/blockPro-libp2p
    #command: bash -c "npm run start3"
    container_name: peer3
    ports:
    - "8339:8339"
    stdin_open: true
    tty: true
    privileged: true
    networks:
      static:
        ipv4_address: 172.22.0.4

networks:
  static:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1   