version: "2"
services:
  regtest:
    build:
      context: .
      dockerfile: Dockerfile
    image: "doichain/node-only"
    container_name: regtest
    environment:
      - REGTEST=true
      - RPC_ALLOW_IP=0.0.0.0/0
      - RPC_PASSWORD=adminpw
    ports:
      - "8338:8338"
      - "8339:8339"
      - "18332:18332"
    stdin_open: true
    tty: true
    privileged: true





